<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-27T21:50:16 IST" name="Suite" finished-at="2023-07-27T21:50:24 IST" duration-ms="8424">
    <groups>
    </groups>
    <test started-at="2023-07-27T21:50:16 IST" name="Test" finished-at="2023-07-27T21:50:24 IST" duration-ms="8424">
      <class name="testsuites.TestNewOpp">
        <test-method is-config="true" signature="browseropening()[pri:0, instance:testsuites.TestNewOpp@3eb738bb]" started-at="2023-07-27T21:50:16 IST" name="browseropening" finished-at="2023-07-27T21:50:22 IST" duration-ms="5747" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browseropening -->
        <test-method signature="excelread([Ljava.lang.String;)[pri:0, instance:testsuites.TestNewOpp@3eb738bb]" started-at="2023-07-27T21:50:23 IST" name="excelread" data-provider="datasendingmethod" finished-at="2023-07-27T21:50:24 IST" duration-ms="785" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@2f4b98f6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- excelread -->
        <test-method is-config="true" signature="failurescreenshot(org.testng.ITestResult)[pri:0, instance:testsuites.TestNewOpp@3eb738bb]" started-at="2023-07-27T21:50:24 IST" name="failurescreenshot" finished-at="2023-07-27T21:50:24 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=excelread status=SUCCESS method=TestNewOpp.excelread([Ljava.lang.String;)[pri:0, instance:testsuites.TestNewOpp@3eb738bb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failurescreenshot -->
        <test-method signature="title()[pri:0, instance:testsuites.TestNewOpp@3eb738bb]" started-at="2023-07-27T21:50:24 IST" name="title" finished-at="2023-07-27T21:50:24 IST" duration-ms="351" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login | Salesforce] but found [Lightning Experience]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login | Salesforce] but found [Lightning Experience]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testsuites.TestNewOpp.title(TestNewOpp.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- title -->
        <test-method is-config="true" signature="failurescreenshot(org.testng.ITestResult)[pri:0, instance:testsuites.TestNewOpp@3eb738bb]" started-at="2023-07-27T21:50:24 IST" name="failurescreenshot" finished-at="2023-07-27T21:50:24 IST" duration-ms="217" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=title status=FAILURE method=TestNewOpp.title()[pri:0, instance:testsuites.TestNewOpp@3eb738bb] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failurescreenshot -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testsuites.TestNewOpp@3eb738bb]" started-at="2023-07-27T21:50:24 IST" name="teardown" finished-at="2023-07-27T21:50:24 IST" duration-ms="224" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testsuites.TestNewOpp -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
